====================================
0-add_integer.py - Add two integers
====================================

Doctest pour la fonction add_integer

Import:
    >>> add_integer = __import__('0-add_integer').add_integer

tests calculs:
    >>> add_integer(1, 2)
    3

    >>> add_integer(96, 2)
    98

    >>> add_integer(98, 2)
    100

    >>> add_integer(100, -2)
    98

    >>> add_integer(95.99, 2.1)
    97

    >>> add_integer(-1, -1)
    -2

    >>> add_integer(0, 0)
    0

tests valeurs par dÃ©faut:
    >>> add_integer(5)
    103

tests float:
    >>> add_integer(1.5, 2)
    3
    >>> add_integer(1, 2.7)
    3
    >>> add_integer(1.2, 2.8)
    3

tests erreurs:
    >>> add_integer("3", 2)
    Traceback (most recent call last):
        ...
    TypeError: a must be an integer

    >>> add_integer(3, "2")
    Traceback (most recent call last):
        ...
    TypeError: b must be an integer

    >>> add_integer(None)
    Traceback (most recent call last):
        ...
    TypeError: a must be an integer

    >>> add_integer(None, 5)
    Traceback (most recent call last):
        ...
    TypeError: a must be an integer

    >>> add_integer(5, None)
    Traceback (most recent call last):
        ...
    TypeError: b must be an integer

    >>> add_integer([1, 2], 3)
    Traceback (most recent call last):
        ...
    TypeError: a must be an integer

    >>> add_integer(3, [1, 2])
    Traceback (most recent call last):
        ...
    TypeError: b must be an integer

tests infini et NaN:
    >>> add_integer(float('inf'), 2)
    Traceback (most recent call last):
        ...
    OverflowError: cannot convert float infinity to integer

    >>> add_integer(2, float('-inf'))
    Traceback (most recent call last):
        ...
    OverflowError: cannot convert float infinity to integer

    >>> add_integer(float('nan'), 2)
    Traceback (most recent call last):
        ...
    ValueError: cannot convert float NaN to integer

tests arguments manquants:
    >>> add_integer()
    Traceback (most recent call last):
        ...
    TypeError: add_integer() missing 1 required positional argument: 'a'
